version: 2

jobs:
  build:
    working_directory: .
    docker:
      - image: docker:17.05.0-ce-git
      - image: circleci/node:latest
    steps:
      - checkout
      - setup_remote_docker
      - run: apt install -y sudo # https://discuss.circleci.com/t/sudo-command-not-found/14208/4
      - run: ls -al /bin/sh && sudo rm /bin/sh && sudo ln -s /bin/bash /bin/sh && ls -al /bin/sh
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@5'
      - run:
          name: Install dependencies
          command: |
            npm install
      
      - run:
          name: Deploying to Docker
          command: |
            docker login -e $DOCKER_HUB_EMAIL -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PASSWORD
            docker tag first-docker $DOCKER_HUB_USER_ID/first-docker
            docker push $DOCKER_HUB_USER_ID/first-docker
