version: 2

jobs:
  build:
    working_directory: ~/app
    docker: 
      - image: cimg/node:21.7.1
    steps:
      - checkout
      - setup_remote_docker 
      - run:
          name: node version
          command: node --version
      - run:
          name: Clear npm Cache
          command: npm cache clean --force
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build the services
          command: docker build -t first-docker ./app
      - run:
          name: Deploying to Docker
          command: |
            docker login -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PASSWORD
            docker tag first-docker $DOCKER_HUB_USER_ID/first-docker
            docker push $DOCKER_HUB_USER_ID/first-docker
