version: 2

jobs:
  build:
    working_directory: ~/app
    docker:
      - image:  cimg/base:2022.09 
      #- image: cimg/node:21.7.1
    steps:
      - checkout
      - setup_remote_docker 
      - run:
          name: node version
          command: node --version
      - run:
          name: Clear npm Cache
          command: npm cache clean --force
      - run:
          name: Install dependencies
          command: npm install
      #- run:
      #    name: Build the docker services
      #    command: | 
      #      TAG=0.1.$CIRCLE_BUILD_NUM
      #     docker build -t $DOCKER_HUB_USER_ID/first-docker .
      - run:
          name: Deploying to Docker
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t $DOCKER_HUB_USER_ID/first-docker:$TAG .
            docker login -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PASSWORD
            docker push $DOCKER_HUB_USER_ID/first-docker:$TAG 
